image: node:11.12.0

services:
  - postgres:11.1-alpine

variables:
  POSTGRES_DB: enjoy_test
  POSTGRES_USER: enjoy
  POSTGRES_PASSWORD: enjoy

  TEST_DATABASE_URL: postgres://enjoy:enjoy@postgres:5432/enjoy_test

before_script:
  - yarn
  - yarn knex-test migrate:latest

test:
  script:
    - yarn test
