image: node:11.12.0

services:
  - postgres:12.1

variables:
  POSTGRES_DB: graphql_training_test
  POSTGRES_USER: graphql_training
  POSTGRES_PASSWORD: graphql_training

  TEST_DATABASE_URL: postgres://graphql_training:graphql_training@postgres:5432/graphql_training_test
before_script:
  - yarn
  - yarn knex-test migrate:latest

test:
  script:
    - yarn test
